apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: devops
type: Opaque
stringData:
  objectstorage.yaml: |
    type: S3
    config:
      bucket: "4495-hyperloop-log"
      endpoint: "s3.amazonaws.com"
      access_key: "AQI237OAB"
      secret_key: "+Te6fhGOPfaTk74"
      insecure: false
      signature_version2: false
    prefix: "prometheus/"